use_frameworks!

platform :ios, '8.0'

target 'SLSegmentBarObjCKit_Example' do
  pod 'SLSegmentBarObjCKit', :path => '../'

  target 'SLSegmentBarObjCKit_Tests' do
    inherit! :search_paths

    
  end
end
